### ISSUE TITLE
send open tabs to backend when login

### ISSUE THREAD

**Issue by gamiller** [HindsightTwentyTwenty/extension#107]
When user logs in, in the background script or possibly in the actions take all the current tabs and send them to the backend to create new pages right now. ONLY ON SUCCESSFUL LOGIN

**Comment by gamiller** [comment]
currently as soon as login you send current tab to backend.  we are not sending all tabs- but zach had previously said this was ok?

**Comment by zatannenbaum** [comment]
Are you able to send all current tabs?

The only way this works without sending all of them is if we update what gets sent on active to include the same data that is sent on the new page request
