### ISSUE TITLE
Edit categories todos 

### ISSUE THREAD

**Issue by wandaczerwinski** [HindsightTwentyTwenty/extension#122]
-Should be check to make sure user doesn't try to make two identical categories
-Trim whitespace so empty categories aren't created
-Add onBlur event to make the text area disappear 
-Disable reclicking of buttons unless the user has entered a valid category name
-Add SVGs to edit and delete buttons

**Comment by zatannenbaum** [comment]
@wandaczerwinski can you convert the things on this to do list to issues please?

**Comment by wandaczerwinski** [comment]
If I knew how, I would totally do that. But all of these things are done or no longer relevant! So, closing.
