### ISSUE TITLE
Lookback rectangular hover

### ISSUE THREAD

**Issue by ead12345** [HindsightTwentyTwenty/extension#204]
It wasn't intuitive to me that the titles would change based on just putting my mouse in different rectangles. Maybe make this more exaggerated somehow? Either with the change in the screen or making the rectangles where you hover more exaggerated

**Comment by gamiller** [comment]
Put (and gather) more useful info about the pages we’re visiting 
Have it be a modal, with darkened background and hovered exit box
Fill in the boxes with colors and divide with white lines, have whichever box you are hovered on change color
Possibly have a label on the top that says “hover over the timeline to see more information” (the first time the user hits the page) 
Times shown along the timeline to better convey what that bar is showing
