### ISSUE TITLE
Add button to go to current history on lookback

### ISSUE THREAD

**Issue by jaburtonsf** [HindsightTwentyTwenty/extension#211]
I was scrolling back in the lookback view and wanted to go forward to see my current history but the calendar / time selection was a bit buggy and I ended up having to click the right arrow to move forward a couple of days. A button to automatically advance to the current time would be helpful.

Additionally, it might be useful to show both the calendar and the up/down arrows for time of day when users are choosing a specific part of their history to go back to, instead of having to toggle back and forth between the two.

**Comment by gamiller** [comment]
in development 👍
