### ISSUE TITLE
Links to pages from categories page disappear after clicked

### ISSUE THREAD

**Issue by jaburtonsf** [HindsightTwentyTwenty/extension#212]
I marked some pages down under various categories but when I click the links to specific pages from the categories view, and then navigate back to the categories view, the names of the sites have disappeared. This is obviously a small fix but important not to have site names disappear

Addendum: This only happens sometimes... it might only be when you have multiple pages marked under the same category and you click on any link but the first one..?

**Comment by zatannenbaum** [comment]
@trk17 @gamiller @sgarg17 @wandaczerwinski has anyone noticed this recently? If not, let's close it
