### ISSUE TITLE
Get rid of mini scroll bars on right side of each search result

### ISSUE THREAD

**Issue by emilyold** [HindsightTwentyTwenty/extension#218]
Here is a screenshot. It seems like maybe the star icon is too big?

<img width="180" alt="screen shot 2017-02-07 at 6 00 15 pm" src="https://cloud.githubusercontent.com/assets/14880723/22807509/5e931f40-eef5-11e6-82ef-2d99b61de95c.png">

**Comment by gamiller** [comment]
in progress
