### ISSUE TITLE
Refine search so that not every site is returned in the search

### ISSUE THREAD

**Issue by emilyold** [HindsightTwentyTwenty/extension#219]
It seems like when you search every site in my history is returned. The most relevant ones are at the top, but many of the ones that are returned have nothing to do with my search. (e.g. I visited the "Canada" Wikipedia page, and although this was the first result returned, it also returned the site for CS31 this term which does not even contain the word "Canada").

**Comment by gamiller** [comment]
Cool, if a page it is below a certain relevance threshold we should not return it

**Comment by gamiller** [comment]
we will make this on the backend.
