### ISSUE TITLE
Custom Category Colors

### ISSUE THREAD

**Issue by wandaczerwinski** [HindsightTwentyTwenty/extension#227]
Make it so that users can input hex values for custom category colors.

**Comment by zatannenbaum** [comment]
I'm not sure if you mean a user has to enter a 6 digit hex value or not, but I think the user should be given a color wheel or something rather than an input field for a 6 digit hex value

**Comment by wandaczerwinski** [comment]
Talked with Zach and Tim about storing a string for each user on the backend and parsing it on the frontend.
