### ISSUE TITLE
Min-Width for Tab view

### ISSUE THREAD

**Issue by zatannenbaum** [HindsightTwentyTwenty/extension#261]
currently you can compress the window as much as you want which messes with a lot of the format of the page and hides the tabs at the top. If instead there was a min-width the page would stop shrinking at some point and become scrollable so that formatting and styling are not lost and the app still looks pretty

**Comment by gamiller** [comment]
these are the tabs in the header at the top of the page- "categories" "manage" etc. maybe we make the whole div min-width?
