### ISSUE TITLE
Categories rework

### ISSUE THREAD

**Issue by gamiller** [HindsightTwentyTwenty/extension#265]
-star/unstar
-need to be able to create new category on this page- (and add pages to current categories by pasting the url in)
-need to be able to delete pages from categories
-i think we need to have a discussion about the sidebar- i think it's currently confusing to use
-eyeball falls off of the urlbars when you condense the page

**Comment by wandaczerwinski** [comment]
Sidebar fixed by #289

**Comment by wandaczerwinski** [comment]
All of these are now being addressed by #290
