### ISSUE TITLE
categories page cleanup

### ISSUE THREAD

**Issue by wandaczerwinski** [HindsightTwentyTwenty/extension#290]
General: 
- [x] *Make sure we only call fetchCats once*
~Paginate the categories page~
~Autocomplete?~ (will do during spring) 

Sidebar: 
- [x] be able to add cat from here
 ~sort categories in alphabetical order~
- [x] remove 1px divot under search bar
- [x] change hover style
- [x] keep power buttons at top of sidebar
- [x] add ellipsis to long cat names 
- [x] scroll styles? 
- [x] Add right border 
- [x] make whole title clickable

PageUrlBar: 
- [x] fix show starred
- [x] Add cats to existing pages 
- [x] fix eye position
- [ ] Url bar to add new pages to categories 
- [x] Be able to change color of added cat

**Comment by wandaczerwinski** [comment]
Also fixed horrible bug where categories weren't deleting exactly right from page url bars. 🐛

**Comment by zatannenbaum** [comment]
I don't think the categories page should be paginated, maybe there can be options or see all vs 10 per page or something but I think it makes it less accessible to paginate it

**Comment by wandaczerwinski** [comment]
Okay, I won't paginate it then! Thanks for the feedback 🛩

**Comment by wandaczerwinski** [comment]
Will save autocomplete for spring work. Don't think it's a huge issue since you can see all of your cats in the sidebar.

**Comment by wandaczerwinski** [comment]
Almost all addressed by #327. Now just have to build component allowing user to add new pages to cats.

**Comment by sgarg17** [comment]
working on finishing up autocomplete component now that can be reused here

**Comment by wandaczerwinski** [comment]
After some discussion of whether its useful to be able to add pages to cats, have decided to hold off on that until spring term. Will open another issue.
