### ISSUE TITLE
categories bugs

### ISSUE THREAD

**Issue by gamiller** [HindsightTwentyTwenty/extension#293]
- [x] left bar cuts into the top nav bar (little grey line)
- [x] make title edit box more prominent (change color background)
- [x] option to edit color on categories
- [x] shouldnt have blank space around the urlbars (not reactive)
- [x] still cant star things
- [x] allow people to select starred when no categories are selected and show things that are only starred and not categorized
- [x] definitive boxing around the categories- color or line

**Comment by wandaczerwinski** [comment]
- [x] changing category name makes color change back to default orange

**Comment by wandaczerwinski** [comment]
Changing the category name color back to default orange was also my fault, not backend issue so wheee!!!
