### ISSUE TITLE
Categories Page "Select Category To See Pages" Welcome Screen

### ISSUE THREAD

**Issue by trk17** [HindsightTwentyTwenty/extension#318]
When you first go to the category page or no categories are selected we should have a message saying to see bars first select a category in the space where the bars are shown.

**Comment by wandaczerwinski** [comment]
Good idea. This displays every time you hit the cats page until you click on a category. Once you see URL bars, it hides. 
<img width="877" alt="screen shot 2017-03-06 at 11 12 49 am" src="https://cloud.githubusercontent.com/assets/19778184/23618292/e0f68aa0-025d-11e7-90fb-91ec15c431dd.png">

**Comment by sgarg17** [comment]
do you think we can change the "pencil" and "trashcan" text to the pencil and trashcan icons instead?

**Comment by wandaczerwinski** [comment]
<img width="878" alt="screen shot 2017-03-06 at 11 52 21 am" src="https://cloud.githubusercontent.com/assets/19778184/23619960/60994036-0263-11e7-8c05-3f60da2a8cf6.png">
