### ISSUE TITLE
minutes active is 0 often

### ISSUE THREAD

**Issue by gamiller** [HindsightTwentyTwenty/extension#319]
why is minutes active usually 0?
are we not taking into consideration being on the page for 30 secs or is it an issue with that request to the backend?

**Comment by trk17** [comment]
I think it might be getting rounded down? Spending less than a minute on a bunch of sites doesn't that seem odd. Might want to round these up to 1 minutes though.

I'll check it out.

**Comment by gamiller** [comment]
@trk17 thats what i assumed, but it seems like it would look better as 1 than 0

**Comment by zatannenbaum** [comment]
@trk17 @gamiller it's also possible this is a backend issue on the active endpoint, but not sure
