### ISSUE TITLE
Give users ability to add certain pages to categories 

### ISSUE THREAD

**Issue by wandaczerwinski** [HindsightTwentyTwenty/extension#330]
In the same way we can add cats to pages, should we be able to do the reverse? Basically, should a user be able to go to the cats page and type in a url (like smittenkitchen.com) and categorize it under recipes? 

I think no, because if you can remember the page url then it's probably just a domain instead of a specific article/recipe/etc. Seems not useful, especially after we implement the sessions feature.

**Comment by zatannenbaum** [comment]
Chrome doesn't let you add bookmarks from their bookmark manager. I don't think this is a necessary feature
