### ISSUE TITLE
Basic Redesign of Categories Page

### ISSUE THREAD

**Issue by zatannenbaum** [HindsightTwentyTwenty/extension#84]
Update display to make more user friendly and straightforward

**Comment by wandaczerwinski** [comment]
Some progress has been made in this regard (categories can now be deleted and edited, and the way results are returned is more intuitive), but definitely more work to do.

**Comment by wandaczerwinski** [comment]
Will open a different issue for one more feature we need (labeling url bars with their respective categories) but for now will close this bb, as we are definitely ready for user testing.
