### ISSUE TITLE
Add functionality to blacklisting component

### ISSUE THREAD

**Issue by zatannenbaum** [HindsightTwentyTwenty/extension#88]
User should be able to add/remove/edit their blacklisted sites

**Comment by wandaczerwinski** [comment]
From discussion with Tim: Blacklisted site visits should not be recorded for the duration which the site is blacklisted. If the user "unblacklists" a site, they shouldn't be able to see it again in their history; it's gone. Distinction between this and selectively displaying page visits based on some feature (ie category).
